const sample = (array) => array[Math.floor(Math.random() * array.length)];

const ANIMALS = 'aardvark abyssinian affenpinscher akbash akita albatross alligator angelfish angora ant anteater antelope argentino armadillo audemer avocet axolotl aye baboon badger balinese bandicoot barb barnacle barracuda bat beagle bear beaver bee bee-eater beetle bernard binturong bird birman bison bloodhound blue boar bobcat bombay bongo bonobo booby bordeaux bracke budgerigar buffalo bulldog bullfrog burmese butterfly buzzard caiman camel capuchin capybara caracal cassowary cat caterpillar catfish cattle centipede chameleon chamois cheetah chicken chihuahua chimpanzee chin chinchilla chinook chipmunk chow cichlid civet clam coati cockroach collie coon coonhound coral corgi cougar cow coyote crab crane crocodile cuscus cuttlefish dachsbracke dachshund dalmatian dane deer devil dhole dingo discus dodo dog dogfish dollar dolphin donkey dormouse dragon dragonfly drever duck dugong dunker eagle earwig echidna eel elephant eleuth emperor emu falcon ferret fish flamingo flounder fly forest fossa fousek fowl fox foxhound frigatebird frise frog gar gecko gerbil gharial gibbon giraffe goat goose gopher gorilla grasshopper greyhound grouse guppy hamster hare harrier havanese hedgehog heron himalayan hippopotamus hornet horse hound human hummingbird husky hyena hyrax ibis iguana impala indri insect jackal jaguar javanese jellyfish kakapo kangaroo kingfisher kiwi koala kudu labradoodle ladybird lemming lemur leopard liger lion lionfish lizard llama lobster loon lynx macaque macaw magpie malamute maltese mammoth manatee mandrill markhor marmoset mastiff mau mayfly meerkat millipede mist mole molly mongoose mongrel monkey monster moorhen moose moth mouse mule neanderthal newfoundland newt nightingale numbat ocelot octopus okapi olm opossum orang-utan oriole ostrich otter owl oyster pademelon panda panther paradise parrot peacock peccary pekingese pelican penguin persian pheasant pig pika pike pinscher piranha platypus pointer poodle porcupine possum prawn puffin pug puma quail quetzal quokka quoll rabbit raccoon ragdoll rat rattlesnake ray reindeer retriever rhinoceros robin rottweiler russel salamander saola schnauzer scorpion seahorse seal serval setter shark sheep sheepdog shepherd shrew shrimp siamese siberian skater skunk sloth slug snail snake snowshoe somali spaniel sparrow spider spitz sponge spoonbill squid squirrel squirt starfish stingray stoat swan tamarin tang tapir tarantula tarsier termite terrier tetra tiffany tiger toad tortoise toucan tropicbird tuatara turkey turtle tzu uakari uguisu umbrellabird urchin vole vulture wallaby walrus warthog wasp weasel whale whippet wildebeest wolf wolfhound wolverine wombat woodlouse woodpecker worm wrasse yak zebra zebu zonkey zorse'.split(' ');

export default (n) => {
  if (isNaN(n)) {
    return sample(ANIMALS);
  }
  return ANIMALS[n % ANIMALS.length];
};
